//CREATE A NEW SECRET AND DEFINE BEST STRATEGY TO INJECT HERE
export const jwtConstants = {
    secret: 'DO NOT USE THIS VALUE. INSTEAD, CREATE A COMPLEX SECRET AND KEEP IT SAFE OUTSIDE OF THE SOURCE CODE.',
};